name: Update Proxies

on:
  schedule:
    - cron: "0 */6 * * *" # Run every 6 hours
  workflow_dispatch: # Allow manual triggers

jobs:
  update-proxies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}

      - name: Set up Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Update proxies
        run: |
          # Create directories
          mkdir -p data/latest/types/{http,socks4,socks5}

          # Get current date/time
          YEAR_MONTH=$(date +"%Y-%m")
          DAY=$(date +"%d")
          HOUR=$(date +"%H")
          HOUR_ROUNDED=$(( ($HOUR / 6) * 6 ))
          HOUR_FORMATTED=$(printf "%02d-00" $HOUR_ROUNDED)
          mkdir -p "data/$YEAR_MONTH/$DAY/$HOUR_FORMATTED"

          # Fetch proxies
          RESPONSE=$(curl -s "http://api.proxyprovider.net/api/free-proxies/all")

          # Save to files
          echo "$RESPONSE" > "data/$YEAR_MONTH/$DAY/$HOUR_FORMATTED/proxies.json"
          echo "$RESPONSE" > "data/latest/proxies.json"

          # Extract IP:PORT for all proxies
          cat "data/latest/proxies.json" | grep -o '"ipPort":"[^"]*"' | cut -d'"' -f4 > "data/$YEAR_MONTH/$DAY/$HOUR_FORMATTED/proxies.txt"
          cat "data/latest/proxies.json" | grep -o '"ipPort":"[^"]*"' | cut -d'"' -f4 > "data/latest/proxies.txt"

          # Extract JSON by type
          cat "data/latest/proxies.json" | jq '[.data[] | select(.type == "http")]' > "data/latest/types/http/proxies.json" 2>/dev/null || echo "[]" > "data/latest/types/http/proxies.json"
          cat "data/latest/proxies.json" | jq '[.data[] | select(.type == "socks4")]' > "data/latest/types/socks4/proxies.json" 2>/dev/null || echo "[]" > "data/latest/types/socks4/proxies.json"
          cat "data/latest/proxies.json" | jq '[.data[] | select(.type == "socks5")]' > "data/latest/types/socks5/proxies.json" 2>/dev/null || echo "[]" > "data/latest/types/socks5/proxies.json"

          # Extract IP:PORT by type
          cat "data/latest/proxies.json" | jq -r '.data[] | select(.type == "http") | .ipPort' > "data/latest/types/http/proxies.txt" 2>/dev/null || touch "data/latest/types/http/proxies.txt"
          cat "data/latest/proxies.json" | jq -r '.data[] | select(.type == "socks4") | .ipPort' > "data/latest/types/socks4/proxies.txt" 2>/dev/null || touch "data/latest/types/socks4/proxies.txt"
          cat "data/latest/proxies.json" | jq -r '.data[] | select(.type == "socks5") | .ipPort' > "data/latest/types/socks5/proxies.txt" 2>/dev/null || touch "data/latest/types/socks5/proxies.txt"

      - name: Commit and push changes
        env:
          GH_TOKEN: ${{ secrets.PAT }}
        run: |
          git add data/
          git commit -m "Update proxies - $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
          git push https://${GH_TOKEN}@github.com/$GITHUB_REPOSITORY.git HEAD:${GITHUB_REF}
