name: Update Proxies

on:
  schedule:
    - cron: "0 */6 * * *" # Run every 6 hours
  workflow_dispatch: # Allow manual triggers

jobs:
  update-proxies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'

      - name: Update proxies
        run: |
          # Create directories
          mkdir -p data/latest/types/{http,socks4,socks5}

          # Get current date/time
          YEAR_MONTH=$(date +"%Y-%m")
          DAY=$(date +"%d")
          HOUR=$(date +"%H")
          HOUR_ROUNDED=$(( ($HOUR / 6) * 6 ))
          HOUR_FORMATTED=$(printf "%02d-00" $HOUR_ROUNDED)
          mkdir -p "data/$YEAR_MONTH/$DAY/$HOUR_FORMATTED"

          # Fetch proxies
          RESPONSE=$(curl -s "http://api.proxyprovider.net/api/free-proxies/all")

          # Save to files
          echo "$RESPONSE" > "data/$YEAR_MONTH/$DAY/$HOUR_FORMATTED/proxies.json"
          echo "$RESPONSE" > "data/latest/proxies.json"

          # Extract IP:PORT
          echo "$RESPONSE" | grep -o '"ipPort":"[^"]*"' | cut -d'"' -f4 > "data/$YEAR_MONTH/$DAY/$HOUR_FORMATTED/proxies.txt"
          echo "$RESPONSE" | grep -o '"ipPort":"[^"]*"' | cut -d'"' -f4 > "data/latest/proxies.txt"

          # Extract by type
          echo "$RESPONSE" | grep -o '"type":"http"[^}]*}' > "data/latest/types/http/proxies.json"
          echo "$RESPONSE" | grep -o '"type":"socks4"[^}]*}' > "data/latest/types/socks4/proxies.json"
          echo "$RESPONSE" | grep -o '"type":"socks5"[^}]*}' > "data/latest/types/socks5/proxies.json"

          # Extract IP:PORT by type
          echo "$RESPONSE" | grep -o '"type":"http"[^}]*"ipPort":"[^"]*"' | grep -o '"ipPort":"[^"]*"' | cut -d'"' -f4 > "data/latest/types/http/proxies.txt"
          echo "$RESPONSE" | grep -o '"type":"socks4"[^}]*"ipPort":"[^"]*"' | grep -o '"ipPort":"[^"]*"' | cut -d'"' -f4 > "data/latest/types/socks4/proxies.txt"
          echo "$RESPONSE" | grep -o '"type":"socks5"[^}]*"ipPort":"[^"]*"' | grep -o '"ipPort":"[^"]*"' | cut -d'"' -f4 > "data/latest/types/socks5/proxies.txt"

      - name: Commit and push changes
        run: |
          git add data/
          git commit -m "Update proxies - $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
          git push
